/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[Object.keys(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// core/BinderService.ts
var BinderService_exports = {};
__export(BinderService_exports, {
  BinderService: () => BinderService
});
var BinderService;
var init_BinderService = __esm({
  "core/BinderService.ts"() {
    BinderService = class {
      constructor(app) {
        this.app = app;
        this.state = {
          entries: []
        };
      }
      log(type, message, relatedFile, details) {
        const entry = {
          id: crypto.randomUUID(),
          timestamp: Date.now(),
          type,
          message,
          relatedFile,
          details
        };
        this.state.entries.unshift(entry);
        if (this.state.entries.length > 1e3) {
          this.state.entries = this.state.entries.slice(0, 1e3);
        }
      }
      getEntries() {
        return this.state.entries;
      }
      clear() {
        this.state.entries = [];
      }
    };
  }
});

// core/GroupService.ts
var GroupService_exports = {};
__export(GroupService_exports, {
  GroupService: () => GroupService
});
var import_obsidian, GroupService;
var init_GroupService = __esm({
  "core/GroupService.ts"() {
    import_obsidian = __toModule(require("obsidian"));
    GroupService = class {
      constructor(app) {
        this.app = app;
      }
      validateQuery(query) {
        return __async(this, null, function* () {
          var _a, _b, _c;
          if (!query || query.trim() === "") {
            return { valid: true };
          }
          const dataviewAPI = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api;
          if (!dataviewAPI) {
            return { valid: false, error: "Dataview plugin not found" };
          }
          try {
            dataviewAPI.pages(query);
            return { valid: true };
          } catch (e) {
            return { valid: false, error: e.message };
          }
        });
      }
      matchesQuery(file, query) {
        var _a, _b, _c;
        if (!query || query.trim() === "") {
          return true;
        }
        const dataviewAPI = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api;
        if (!dataviewAPI) {
          console.warn("[Curator] Dataview plugin not found or API not available.");
          return false;
        }
        try {
          const pages = dataviewAPI.pages(query);
          for (const page of pages) {
            if (page.file && page.file.path === file.path) {
              return true;
            }
          }
          return false;
        } catch (error) {
          console.error(`[Curator] Error executing Dataview query: ${query}`, error);
          return false;
        }
      }
      getMatchingFiles(query) {
        var _a, _b, _c;
        if (!query || query.trim() === "") {
          return this.app.vault.getFiles();
        }
        const dataviewAPI = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api;
        if (!dataviewAPI) {
          return [];
        }
        try {
          const pages = dataviewAPI.pages(query);
          const files = [];
          for (const page of pages) {
            const file = this.app.vault.getAbstractFileByPath(page.file.path);
            if (file instanceof import_obsidian.TFile) {
              files.push(file);
            }
          }
          return files;
        } catch (error) {
          console.error(`[Curator] Error executing Dataview query: ${query}`, error);
          return [];
        }
      }
    };
  }
});

// core/TriggerService.ts
var TriggerService_exports = {};
__export(TriggerService_exports, {
  TriggerService: () => TriggerService
});
var import_obsidian2, TriggerService;
var init_TriggerService = __esm({
  "core/TriggerService.ts"() {
    import_obsidian2 = __toModule(require("obsidian"));
    TriggerService = class {
      constructor(app) {
        this.listeners = new Map();
        this.eventRefs = [];
        this.lastActiveFile = null;
        this.dirtyFiles = new Set();
        this.app = app;
      }
      registerTrigger(trigger, callback) {
        this.listeners.set(trigger, callback);
      }
      clearTriggers() {
        this.listeners.clear();
      }
      initializeListeners() {
        this.eventRefs.forEach((ref) => this.app.vault.offref(ref));
        this.eventRefs = [];
        this.eventRefs.push(this.app.vault.on("modify", (file) => {
          if (file instanceof import_obsidian2.TFile) {
            this.dirtyFiles.add(file.path);
          }
        }));
        this.eventRefs.push(this.app.workspace.on("active-leaf-change", (leaf) => {
          this.handleActiveLeafChange(leaf);
        }));
        setTimeout(() => {
          this.handleStartup();
        }, 3e3);
        window.setInterval(() => {
          this.handleSchedule();
        }, 60 * 1e3);
      }
      handleActiveLeafChange(leaf) {
        var _a;
        const currentFile = ((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.file) instanceof import_obsidian2.TFile ? leaf.view.file : null;
        if (this.lastActiveFile && this.lastActiveFile !== currentFile) {
          if (this.dirtyFiles.has(this.lastActiveFile.path)) {
            this.fireTriggers("change_from", this.lastActiveFile);
            this.fireTriggers("change_to", this.lastActiveFile);
            this.dirtyFiles.delete(this.lastActiveFile.path);
          }
        }
        this.lastActiveFile = currentFile;
      }
      handleStartup() {
        const files = this.app.vault.getMarkdownFiles();
        files.forEach((file) => {
          this.fireTriggers("startup", file);
        });
      }
      handleSchedule() {
        const now = new Date();
        const currentDay = now.getDay();
        const currentHour = now.getHours();
        const currentMinute = now.getMinutes();
        const timeString = `${String(currentHour).padStart(2, "0")}:${String(currentMinute).padStart(2, "0")}`;
        for (const [trigger, callback] of this.listeners) {
          if (trigger.type === "schedule") {
            if (trigger.days && !trigger.days.includes(currentDay))
              continue;
            if (trigger.time === timeString) {
              const files = this.app.vault.getMarkdownFiles();
              files.forEach((file) => callback(file));
            }
          }
        }
      }
      fireTriggers(type, file) {
        for (const [trigger, callback] of this.listeners) {
          if (trigger.type === type) {
            callback(file);
          }
        }
      }
      unload() {
        this.eventRefs.forEach((ref) => this.app.vault.offref(ref));
        this.eventRefs = [];
        this.listeners.clear();
      }
    };
  }
});

// core/ActionService.ts
var ActionService_exports = {};
__export(ActionService_exports, {
  ActionService: () => ActionService
});
var import_obsidian3, ActionService;
var init_ActionService = __esm({
  "core/ActionService.ts"() {
    import_obsidian3 = __toModule(require("obsidian"));
    ActionService = class {
      constructor(app, binder) {
        this.app = app;
        this.binder = binder;
      }
      executeAction(file, action) {
        return __async(this, null, function* () {
          try {
            switch (action.type) {
              case "move":
                if (action.config.folder) {
                  yield this.moveFile(file, action.config.folder);
                }
                break;
              case "rename":
                yield this.renameFile(file, action.config);
                break;
              case "tag":
                if (action.config.tag) {
                  yield this.tagFile(file, action.config.tag, action.config.operation || "add");
                }
                break;
              case "update":
                if (action.config.key) {
                  yield this.updateProperty(file, action.config.key, action.config.value || "");
                }
                break;
              default:
                this.binder.log("warning", `Unknown action type: ${action.type}`, file.path);
            }
          } catch (error) {
            this.binder.log("error", `Failed to execute action ${action.type}`, file.path, error);
            throw error;
          }
        });
      }
      moveFile(file, folder) {
        return __async(this, null, function* () {
          let targetFolder = (0, import_obsidian3.normalizePath)(folder);
          const folderExists = yield this.app.vault.adapter.exists(targetFolder);
          if (!folderExists) {
            yield this.app.vault.createFolder(targetFolder);
            this.binder.log("info", `Created folder ${targetFolder}`);
          }
          const targetPath = (0, import_obsidian3.normalizePath)(`${targetFolder}/${file.name}`);
          if (targetPath === file.path) {
            return;
          }
          const targetFileExists = yield this.app.vault.adapter.exists(targetPath);
          if (targetFileExists) {
            this.binder.log("warning", `File ${targetPath} already exists. Skipping move.`, file.path);
            return;
          }
          yield this.app.fileManager.renameFile(file, targetPath);
          this.binder.log("success", `Moved file to ${targetFolder}`, targetPath);
        });
      }
      renameFile(file, config) {
        return __async(this, null, function* () {
          var _a;
          let newName = file.basename;
          if (config.prefix) {
            newName = `${config.prefix}${newName}`;
          }
          if (config.suffix) {
            newName = `${newName}${config.suffix}`;
          }
          if (newName === file.basename)
            return;
          const targetPath = (0, import_obsidian3.normalizePath)(`${(_a = file.parent) == null ? void 0 : _a.path}/${newName}.${file.extension}`);
          if (yield this.app.vault.adapter.exists(targetPath)) {
            this.binder.log("warning", `File ${targetPath} already exists. Skipping rename.`, file.path);
            return;
          }
          yield this.app.fileManager.renameFile(file, targetPath);
          this.binder.log("success", `Renamed file to ${newName}`, targetPath);
        });
      }
      tagFile(file, tag, operation) {
        return __async(this, null, function* () {
          yield this.app.fileManager.processFrontmatter(file, (frontmatter) => {
            let tags = frontmatter["tags"];
            if (!tags)
              tags = [];
            if (!Array.isArray(tags))
              tags = [tags];
            const targetTag = tag.startsWith("#") ? tag.substring(1) : tag;
            if (operation === "add") {
              if (!tags.includes(targetTag)) {
                tags.push(targetTag);
                this.binder.log("success", `Added tag #${targetTag}`, file.path);
              }
            } else if (operation === "remove") {
              const index = tags.indexOf(targetTag);
              if (index > -1) {
                tags.splice(index, 1);
                this.binder.log("success", `Removed tag #${targetTag}`, file.path);
              }
            }
            frontmatter["tags"] = tags;
          });
        });
      }
      updateProperty(file, key, value) {
        return __async(this, null, function* () {
          yield this.app.fileManager.processFrontmatter(file, (frontmatter) => {
            frontmatter[key] = value;
            this.binder.log("success", `Updated property ${key} to ${value}`, file.path);
          });
        });
      }
    };
  }
});

// core/RulesetService.ts
var RulesetService_exports = {};
__export(RulesetService_exports, {
  RulesetService: () => RulesetService
});
var RulesetService;
var init_RulesetService = __esm({
  "core/RulesetService.ts"() {
    RulesetService = class {
      constructor(app, triggerService, groupService, binder, actionService) {
        this.rulesets = [];
        this.app = app;
        this.triggerService = triggerService;
        this.groupService = groupService;
        this.binder = binder;
        this.actionService = actionService;
      }
      updateConfig(config) {
        this.rulesets = config.rulesets;
        this.triggerService.clearTriggers();
        this.rulesets.forEach((ruleset) => {
          if (ruleset.enabled) {
            this.triggerService.registerTrigger(ruleset.trigger, (file) => {
              this.handleTrigger(ruleset, file);
            });
          }
        });
      }
      handleTrigger(ruleset, file) {
        return __async(this, null, function* () {
          this.binder.log("info", `Processing Ruleset: ${ruleset.name}`, file.path);
          if (ruleset.trigger.query) {
            const matchesScope = this.groupService.matchesQuery(file, ruleset.trigger.query);
            if (!matchesScope) {
              return;
            }
          }
          for (const rule of ruleset.rules) {
            let match = true;
            let query = rule.query;
            if (rule.useTriggerQuery) {
              query = ruleset.trigger.query || "";
            }
            if (query) {
              match = this.groupService.matchesQuery(file, query);
            }
            if (match) {
              this.binder.log("info", `Rule matched. Executing actions.`, file.path);
              yield this.executeActions(rule.actions, file);
            }
          }
        });
      }
      executeActions(actions, file) {
        return __async(this, null, function* () {
          for (const action of actions) {
            try {
              yield this.actionService.executeAction(file, action);
            } catch (error) {
              this.binder.log("error", `Failed to execute action ${action.type}`, file.path, error);
            }
          }
        });
      }
      dryRun(rulesetId) {
        return __async(this, null, function* () {
          const ruleset = this.rulesets.find((r) => r.id === rulesetId);
          if (!ruleset)
            return [];
          let candidateFiles = [];
          if (ruleset.trigger.query) {
            candidateFiles = this.groupService.getMatchingFiles(ruleset.trigger.query);
          } else {
            candidateFiles = this.app.vault.getMarkdownFiles();
          }
          const results = [];
          for (const file of candidateFiles) {
            const fileActions = [];
            for (const rule of ruleset.rules) {
              let match = true;
              let query = rule.query;
              if (rule.useTriggerQuery) {
                query = ruleset.trigger.query || "";
              }
              if (query) {
                match = this.groupService.matchesQuery(file, query);
              }
              if (match) {
                rule.actions.forEach((action) => {
                  let desc = action.type;
                  if (action.type === "move")
                    desc += ` to ${action.config.folder}`;
                  else if (action.type === "tag")
                    desc += ` ${action.config.operation} ${action.config.tag}`;
                  else if (action.type === "rename")
                    desc += ` (prefix: ${action.config.prefix}, suffix: ${action.config.suffix})`;
                  else if (action.type === "update")
                    desc += ` ${action.config.key} = ${action.config.value}`;
                  fileActions.push(desc);
                });
              }
            }
            if (fileActions.length > 0) {
              results.push({ file, actions: fileActions });
            }
          }
          return results;
        });
      }
    };
  }
});

// main.ts
__export(exports, {
  default: () => AutoNoteMover
});
var import_obsidian9 = __toModule(require("obsidian"));
init_BinderService();
init_GroupService();
init_TriggerService();
init_ActionService();
init_RulesetService();

// ui/CuratorSettingsTab.ts
var import_obsidian8 = __toModule(require("obsidian"));

// ui/components/RulesTab.ts
var import_obsidian6 = __toModule(require("obsidian"));

// ui/components/FolderSuggest.ts
var import_obsidian4 = __toModule(require("obsidian"));
var FolderSuggest = class {
  constructor(app, inputEl) {
    this.app = app;
    this.inputEl = inputEl;
    this.suggestions = [];
    this.isOpen = false;
    this.selectedIndex = -1;
    this.containerEl = createDiv("suggestion-container");
    this.containerEl.style.position = "absolute";
    this.containerEl.style.zIndex = "1000";
    this.containerEl.style.display = "none";
    this.containerEl.style.maxHeight = "200px";
    this.containerEl.style.overflowY = "auto";
    this.containerEl.style.backgroundColor = "var(--background-secondary)";
    this.containerEl.style.border = "1px solid var(--background-modifier-border)";
    document.body.appendChild(this.containerEl);
    this.inputEl.addEventListener("input", this.onInput.bind(this));
    this.inputEl.addEventListener("blur", () => setTimeout(() => this.close(), 200));
    this.inputEl.addEventListener("focus", this.onInput.bind(this));
    this.inputEl.addEventListener("keydown", this.onKeyDown.bind(this));
  }
  onInput() {
    const val = this.inputEl.value;
    this.suggestions = this.getSuggestions(val);
    this.selectedIndex = -1;
    if (this.suggestions.length > 0) {
      this.open();
      this.renderSuggestions();
    } else {
      this.close();
    }
  }
  onKeyDown(e) {
    if (!this.isOpen || this.suggestions.length === 0)
      return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      this.selectedIndex = (this.selectedIndex + 1) % this.suggestions.length;
      this.renderSuggestions();
      this.scrollIntoView();
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      this.selectedIndex = (this.selectedIndex - 1 + this.suggestions.length) % this.suggestions.length;
      this.renderSuggestions();
      this.scrollIntoView();
    } else if (e.key === "Enter") {
      if (this.selectedIndex >= 0 && this.selectedIndex < this.suggestions.length) {
        e.preventDefault();
        this.selectSuggestion(this.suggestions[this.selectedIndex]);
      }
    } else if (e.key === "Escape") {
      this.close();
    }
  }
  scrollIntoView() {
    const selectedEl = this.containerEl.children[this.selectedIndex];
    if (selectedEl) {
      selectedEl.scrollIntoView({ block: "nearest" });
    }
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((file) => {
      if (file instanceof import_obsidian4.TFolder) {
        if (file.path.toLowerCase().contains(lowerCaseInputStr)) {
          folders.push(file);
        }
      }
    });
    return folders;
  }
  renderSuggestions() {
    this.containerEl.empty();
    const rect = this.inputEl.getBoundingClientRect();
    this.containerEl.style.top = `${rect.bottom}px`;
    this.containerEl.style.left = `${rect.left}px`;
    this.containerEl.style.width = `${rect.width}px`;
    this.suggestions.forEach((folder, index) => {
      const item = this.containerEl.createDiv("suggestion-item");
      item.setText(folder.path);
      item.style.padding = "5px";
      item.style.cursor = "pointer";
      if (index === this.selectedIndex) {
        item.style.backgroundColor = "var(--background-modifier-hover)";
        item.addClass("is-selected");
      }
      item.addEventListener("mouseenter", () => {
        this.selectedIndex = index;
        this.renderSuggestions();
      });
      item.addEventListener("mousedown", (e) => {
        e.preventDefault();
        this.selectSuggestion(folder);
      });
    });
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder.path;
    this.inputEl.trigger("input");
    this.close();
  }
  open() {
    this.containerEl.style.display = "block";
    this.isOpen = true;
  }
  close() {
    this.containerEl.style.display = "none";
    this.isOpen = false;
    this.selectedIndex = -1;
  }
};

// ui/components/QueryHelperModal.ts
var import_obsidian5 = __toModule(require("obsidian"));
var QueryHelperModal = class extends import_obsidian5.Modal {
  constructor(app, onSelect) {
    super(app);
    this.templates = [
      {
        name: "Files in Folder with Property",
        description: "Select files in a specific folder that have a property containing specific text.",
        query: 'FROM "Folder/Path" WHERE contains(my_property, "search text")'
      },
      {
        name: "Tagged Notes Missing Property",
        description: "Select notes with a specific tag that do NOT have a certain property.",
        query: "FROM #tag WHERE !my_property"
      },
      {
        name: "Match Filename",
        description: "Select files where the filename contains a specific word.",
        query: 'WHERE contains(file.name, "Project")'
      },
      {
        name: "Relative Date (Created Recently)",
        description: "Select files created in the last 7 days.",
        query: "WHERE file.cday >= date(today) - dur(7 days)"
      },
      {
        name: "Relative Date (Modified Recently)",
        description: "Select files modified in the last 24 hours.",
        query: "WHERE file.mtime >= date(now) - dur(24 hours)"
      },
      {
        name: "Tasks in Specific File",
        description: "Select tasks from a specific file (if using task queries).",
        query: 'FROM "Projects/Active Project.md" WHERE !completed'
      }
    ];
    this.onSelect = onSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Dataview Query Templates" });
    contentEl.createEl("p", { text: "Click a template to insert it into your query field." });
    const list = contentEl.createDiv("query-template-list");
    list.style.display = "flex";
    list.style.flexDirection = "column";
    list.style.gap = "10px";
    this.templates.forEach((template) => {
      const item = list.createDiv("query-template-item");
      item.style.border = "1px solid var(--background-modifier-border)";
      item.style.padding = "10px";
      item.style.borderRadius = "4px";
      item.style.cursor = "pointer";
      item.style.transition = "background-color 0.2s ease";
      item.onmouseover = () => {
        item.style.backgroundColor = "var(--background-secondary)";
      };
      item.onmouseout = () => {
        item.style.backgroundColor = "transparent";
      };
      item.onclick = () => {
        this.onSelect(template.query);
        this.close();
      };
      const header = item.createDiv("query-template-header");
      header.style.fontWeight = "bold";
      header.style.marginBottom = "5px";
      header.setText(template.name);
      const desc = item.createDiv("query-template-desc");
      desc.style.fontSize = "0.9em";
      desc.style.color = "var(--text-muted)";
      desc.style.marginBottom = "5px";
      desc.setText(template.description);
      const code = item.createEl("code");
      code.style.display = "block";
      code.style.padding = "5px";
      code.style.backgroundColor = "var(--background-primary)";
      code.style.borderRadius = "3px";
      code.style.fontFamily = "var(--font-monospace)";
      code.setText(template.query);
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// ui/components/RulesTab.ts
init_GroupService();
var RulesTab = class {
  constructor(app, containerEl, config, onUpdate) {
    this.collapsedItems = new Set();
    this.app = app;
    this.containerEl = containerEl;
    this.config = config;
    this.onUpdate = onUpdate;
    this.groupService = new GroupService(app);
  }
  validateQueryInput(inputEl, statusEl, query) {
    return __async(this, null, function* () {
      statusEl.setText("Checking...");
      statusEl.style.color = "var(--text-muted)";
      const { valid, error } = yield this.groupService.validateQuery(query);
      if (valid) {
        statusEl.setText("Valid");
        statusEl.style.color = "var(--text-success)";
        inputEl.style.borderColor = "";
      } else {
        statusEl.setText(`Invalid: ${error}`);
        statusEl.style.color = "var(--text-error)";
        inputEl.style.borderColor = "var(--text-error)";
      }
    });
  }
  display() {
    this.containerEl.empty();
    this.containerEl.createEl("h3", { text: "Rules Configuration" });
    this.containerEl.createEl("p", { text: "Connect Triggers, Groups, and Jobs to create automated workflows." });
    const globalControls = this.containerEl.createDiv("curator-global-controls");
    new import_obsidian6.Setting(globalControls).addButton((btn) => btn.setButtonText("Expand All").onClick(() => {
      this.collapsedItems.clear();
      this.display();
    })).addButton((btn) => btn.setButtonText("Collapse All").onClick(() => {
      this.config.rulesets.forEach((r) => {
        this.collapsedItems.add(r.id);
        r.rules.forEach((rule) => {
          if (rule.id)
            this.collapsedItems.add(rule.id);
        });
      });
      this.display();
    }));
    new import_obsidian6.Setting(this.containerEl).setName("Add New Ruleset").setDesc("Create a new rule to automate your notes.").addButton((button) => button.setButtonText("Add Ruleset").setCta().onClick(() => {
      this.addRuleset();
    }));
    const rulesetsList = this.containerEl.createDiv("rulesets-list");
    this.config.rulesets.forEach((ruleset, index) => {
      this.renderRuleset(rulesetsList, ruleset, index);
    });
  }
  addRuleset() {
    const newRuleset = {
      id: crypto.randomUUID(),
      name: "New Ruleset",
      enabled: true,
      trigger: { type: "change_to", query: "" },
      rules: []
    };
    this.config.rulesets.push(newRuleset);
    this.onUpdate(this.config);
    this.display();
  }
  renderRuleset(container, ruleset, index) {
    const rulesetContainer = container.createDiv("curator-ruleset-container");
    const header = rulesetContainer.createDiv("curator-ruleset-header");
    if (this.collapsedItems.has(ruleset.id)) {
      header.classList.add("collapsed");
    }
    const nameInputDiv = header.createDiv("curator-ruleset-name-input");
    const nameInput = nameInputDiv.createEl("input", { type: "text", value: ruleset.name });
    nameInput.placeholder = "Ruleset Name";
    nameInput.oninput = () => {
      ruleset.name = nameInput.value;
      this.onUpdate(this.config);
    };
    nameInput.onclick = (e) => e.stopPropagation();
    const controls = header.createDiv("curator-ruleset-controls");
    const toggleLabel = controls.createEl("label");
    toggleLabel.className = "checkbox-container";
    const toggle = toggleLabel.createEl("input", { type: "checkbox" });
    toggle.checked = ruleset.enabled;
    toggle.onclick = (e) => {
      e.stopPropagation();
      ruleset.enabled = toggle.checked;
      this.onUpdate(this.config);
    };
    toggleLabel.createEl("span", { cls: "checkbox-switch" });
    toggleLabel.title = "Enable/Disable Ruleset";
    const moveUpBtn = controls.createEl("button", { cls: "clickable-icon" });
    (0, import_obsidian6.setIcon)(moveUpBtn, "arrow-up");
    moveUpBtn.onclick = (e) => {
      e.stopPropagation();
      if (index > 0) {
        [this.config.rulesets[index - 1], this.config.rulesets[index]] = [this.config.rulesets[index], this.config.rulesets[index - 1]];
        this.onUpdate(this.config);
        this.display();
      }
    };
    if (index === 0)
      moveUpBtn.disabled = true;
    const moveDownBtn = controls.createEl("button", { cls: "clickable-icon" });
    (0, import_obsidian6.setIcon)(moveDownBtn, "arrow-down");
    moveDownBtn.onclick = (e) => {
      e.stopPropagation();
      if (index < this.config.rulesets.length - 1) {
        [this.config.rulesets[index + 1], this.config.rulesets[index]] = [this.config.rulesets[index], this.config.rulesets[index + 1]];
        this.onUpdate(this.config);
        this.display();
      }
    };
    if (index === this.config.rulesets.length - 1)
      moveDownBtn.disabled = true;
    const collapseBtn = controls.createEl("button", { cls: "clickable-icon" });
    (0, import_obsidian6.setIcon)(collapseBtn, this.collapsedItems.has(ruleset.id) ? "chevron-right" : "chevron-down");
    collapseBtn.onclick = (e) => {
      e.stopPropagation();
      if (this.collapsedItems.has(ruleset.id)) {
        this.collapsedItems.delete(ruleset.id);
      } else {
        this.collapsedItems.add(ruleset.id);
      }
      this.display();
    };
    const deleteBtn = controls.createEl("button", { cls: "clickable-icon" });
    (0, import_obsidian6.setIcon)(deleteBtn, "trash");
    deleteBtn.onclick = (e) => {
      e.stopPropagation();
      if (confirm(`Are you sure you want to delete ruleset "${ruleset.name}"?`)) {
        this.config.rulesets.splice(index, 1);
        this.onUpdate(this.config);
        this.display();
      }
    };
    header.onclick = () => {
      if (this.collapsedItems.has(ruleset.id)) {
        this.collapsedItems.delete(ruleset.id);
      } else {
        this.collapsedItems.add(ruleset.id);
      }
      this.display();
    };
    if (this.collapsedItems.has(ruleset.id)) {
      return;
    }
    const body = rulesetContainer.createDiv("curator-ruleset-body");
    const triggerDiv = body.createDiv("curator-trigger-config");
    triggerDiv.createDiv("curator-section-title").setText("Trigger");
    new import_obsidian6.Setting(triggerDiv).setName("When...").addDropdown((dropdown) => dropdown.addOption("change_from", "Notes change from...").addOption("change_to", "Notes change to...").addOption("startup", "Obsidian starts").addOption("schedule", "Scheduled time").addOption("manual", "A command runs").setValue(ruleset.trigger.type).onChange((value) => {
      ruleset.trigger.type = value;
      if (ruleset.trigger.type === "manual")
        ruleset.trigger.commandName = "Run My Rule";
      this.onUpdate(this.config);
      this.display();
    }));
    if (ruleset.trigger.type === "change_from" || ruleset.trigger.type === "change_to") {
      new import_obsidian6.Setting(triggerDiv).setName("Dataview Query").setDesc("Define the set of notes to monitor.").addExtraButton((btn) => btn.setIcon("help-circle").setTooltip("Query Templates").onClick(() => {
        new QueryHelperModal(this.app, (query) => {
          ruleset.trigger.query = query;
          this.onUpdate(this.config);
          this.display();
        }).open();
      })).addTextArea((text) => {
        text.setPlaceholder('FROM "projects" AND #active').setValue(ruleset.trigger.query || "");
        const statusEl = triggerDiv.createDiv("query-status");
        statusEl.style.fontSize = "0.8em";
        statusEl.style.marginTop = "5px";
        this.validateQueryInput(text.inputEl, statusEl, ruleset.trigger.query || "");
        text.inputEl.oninput = (e) => {
          const val = e.target.value;
          ruleset.trigger.query = val;
          this.onUpdate(this.config);
          this.validateQueryInput(text.inputEl, statusEl, val);
        };
      });
    } else if (ruleset.trigger.type === "schedule") {
      new import_obsidian6.Setting(triggerDiv).setName("Time (HH:mm)").addText((text) => text.setPlaceholder("09:00").setValue(ruleset.trigger.time || "").onChange((value) => {
        ruleset.trigger.time = value;
        this.onUpdate(this.config);
      }));
      const daysDiv = triggerDiv.createDiv("days-of-week");
      daysDiv.style.marginTop = "10px";
      daysDiv.createEl("span", { text: "Days: " });
      const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
      days.forEach((day, index2) => {
        const label = daysDiv.createEl("label");
        label.style.marginRight = "10px";
        const checkbox = label.createEl("input", { type: "checkbox" });
        checkbox.checked = ruleset.trigger.days ? ruleset.trigger.days.includes(index2) : true;
        checkbox.onchange = () => {
          if (!ruleset.trigger.days)
            ruleset.trigger.days = [0, 1, 2, 3, 4, 5, 6];
          if (checkbox.checked) {
            if (!ruleset.trigger.days.includes(index2))
              ruleset.trigger.days.push(index2);
          } else {
            ruleset.trigger.days = ruleset.trigger.days.filter((d) => d !== index2);
          }
          this.onUpdate(this.config);
        };
        label.createEl("span", { text: day });
      });
    } else if (ruleset.trigger.type === "manual") {
      new import_obsidian6.Setting(triggerDiv).setName("Command Name").addText((text) => text.setValue(ruleset.trigger.commandName || "").onChange((value) => {
        ruleset.trigger.commandName = value;
        this.onUpdate(this.config);
      }));
    }
    const testBtnDiv = body.createDiv();
    testBtnDiv.style.textAlign = "right";
    testBtnDiv.style.marginBottom = "15px";
    const testBtn = testBtnDiv.createEl("button", { text: "Test Run (Dry Run)" });
    testBtn.onclick = () => __async(this, null, function* () {
      const { RulesetService: RulesetService2 } = yield Promise.resolve().then(() => (init_RulesetService(), RulesetService_exports));
      const { GroupService: GroupService2 } = yield Promise.resolve().then(() => (init_GroupService(), GroupService_exports));
      const { TriggerService: TriggerService2 } = yield Promise.resolve().then(() => (init_TriggerService(), TriggerService_exports));
      const { BinderService: BinderService2 } = yield Promise.resolve().then(() => (init_BinderService(), BinderService_exports));
      const { ActionService: ActionService2 } = yield Promise.resolve().then(() => (init_ActionService(), ActionService_exports));
      const binder = new BinderService2(this.app);
      const groupService = new GroupService2(this.app);
      const triggerService = new TriggerService2(this.app);
      const actionService = new ActionService2(this.app, binder);
      const rulesetService = new RulesetService2(this.app, triggerService, groupService, binder, actionService);
      rulesetService.updateConfig(this.config);
      const results = yield rulesetService.dryRun(ruleset.id);
      const modal = new import_obsidian6.Modal(this.app);
      modal.titleEl.setText(`Dry Run: ${ruleset.name}`);
      if (results.length === 0) {
        modal.contentEl.createEl("p", { text: "No files matched the criteria." });
      } else {
        modal.contentEl.createEl("p", { text: `Found ${results.length} matches:` });
        const list = modal.contentEl.createEl("div");
        list.style.maxHeight = "400px";
        list.style.overflowY = "auto";
        results.forEach((r) => {
          const item = list.createDiv();
          item.style.marginBottom = "5px";
          item.style.borderBottom = "1px solid var(--background-modifier-border)";
          item.createEl("strong", { text: r.file.path });
          const actionsList = item.createEl("ul");
          r.actions.forEach((a) => actionsList.createEl("li", { text: `Action: ${a}` }));
        });
      }
      modal.open();
    });
    const rulesList = body.createDiv("curator-rules-list");
    rulesList.createDiv("curator-section-title").setText("Rules");
    ruleset.rules.forEach((rule, ruleIndex) => {
      if (!rule.id)
        rule.id = crypto.randomUUID();
      const ruleItem = rulesList.createDiv("curator-rule-item");
      const ruleHeader = ruleItem.createDiv("curator-rule-header");
      ruleHeader.createSpan({ text: `Rule ${ruleIndex + 1}`, cls: "curator-rule-title" });
      const ruleControls = ruleHeader.createDiv("curator-controls");
      const rMoveUp = ruleControls.createEl("button", { cls: "clickable-icon" });
      (0, import_obsidian6.setIcon)(rMoveUp, "arrow-up");
      rMoveUp.onclick = (e) => {
        e.stopPropagation();
        if (ruleIndex > 0) {
          [ruleset.rules[ruleIndex - 1], ruleset.rules[ruleIndex]] = [ruleset.rules[ruleIndex], ruleset.rules[ruleIndex - 1]];
          this.onUpdate(this.config);
          this.display();
        }
      };
      if (ruleIndex === 0)
        rMoveUp.disabled = true;
      const rMoveDown = ruleControls.createEl("button", { cls: "clickable-icon" });
      (0, import_obsidian6.setIcon)(rMoveDown, "arrow-down");
      rMoveDown.onclick = (e) => {
        e.stopPropagation();
        if (ruleIndex < ruleset.rules.length - 1) {
          [ruleset.rules[ruleIndex + 1], ruleset.rules[ruleIndex]] = [ruleset.rules[ruleIndex], ruleset.rules[ruleIndex + 1]];
          this.onUpdate(this.config);
          this.display();
        }
      };
      if (ruleIndex === ruleset.rules.length - 1)
        rMoveDown.disabled = true;
      const rCollapse = ruleControls.createEl("button", { cls: "clickable-icon" });
      (0, import_obsidian6.setIcon)(rCollapse, this.collapsedItems.has(rule.id) ? "chevron-right" : "chevron-down");
      rCollapse.onclick = (e) => {
        e.stopPropagation();
        if (this.collapsedItems.has(rule.id)) {
          this.collapsedItems.delete(rule.id);
        } else {
          this.collapsedItems.add(rule.id);
        }
        this.display();
      };
      const rDelete = ruleControls.createEl("button", { cls: "clickable-icon" });
      (0, import_obsidian6.setIcon)(rDelete, "trash");
      rDelete.onclick = (e) => {
        e.stopPropagation();
        ruleset.rules.splice(ruleIndex, 1);
        this.onUpdate(this.config);
        this.display();
      };
      ruleHeader.onclick = () => {
        if (this.collapsedItems.has(rule.id)) {
          this.collapsedItems.delete(rule.id);
        } else {
          this.collapsedItems.add(rule.id);
        }
        this.display();
      };
      if (this.collapsedItems.has(rule.id)) {
        return;
      }
      const ruleBody = ruleItem.createDiv("curator-rule-body");
      const querySetting = new import_obsidian6.Setting(ruleBody);
      querySetting.setName("Condition (Dataview Query)");
      querySetting.setDesc("Leave empty to match all files.");
      if (ruleset.trigger.type === "change_from" || ruleset.trigger.type === "change_to") {
        querySetting.addToggle((toggle2) => toggle2.setValue(rule.useTriggerQuery || false).setTooltip("Use the Trigger's query for this rule").onChange((value) => {
          rule.useTriggerQuery = value;
          this.onUpdate(this.config);
          this.display();
        }));
      }
      if (!rule.useTriggerQuery) {
        querySetting.addExtraButton((btn) => btn.setIcon("help-circle").setTooltip("Query Templates").onClick(() => {
          new QueryHelperModal(this.app, (query) => {
            rule.query = query;
            this.onUpdate(this.config);
            this.display();
          }).open();
        }));
        const queryContainer = ruleBody.createDiv();
        const textArea = queryContainer.createEl("textarea");
        textArea.style.width = "100%";
        textArea.style.minHeight = "60px";
        textArea.style.marginBottom = "10px";
        textArea.placeholder = 'FROM "folder" AND #tag';
        textArea.value = rule.query;
        const statusEl = queryContainer.createDiv("query-status");
        statusEl.style.fontSize = "0.8em";
        statusEl.style.marginBottom = "10px";
        this.validateQueryInput(textArea, statusEl, rule.query);
        textArea.oninput = (e) => {
          const val = e.target.value;
          rule.query = val;
          this.onUpdate(this.config);
          this.validateQueryInput(textArea, statusEl, val);
        };
      } else {
        ruleBody.createEl("p", { text: "Condition: Matches Trigger Scope (Inherited)", cls: "text-muted" });
        if (rule.query)
          rule.query = "";
      }
      const actionsDiv = ruleBody.createDiv("curator-action-list");
      actionsDiv.createDiv("curator-section-title").setText("Actions");
      rule.actions.forEach((action, actionIndex) => {
        const actionItem = actionsDiv.createDiv("curator-action-item");
        const aControls = actionItem.createDiv("curator-controls");
        const aMoveUp = aControls.createEl("button", { cls: "clickable-icon" });
        (0, import_obsidian6.setIcon)(aMoveUp, "arrow-up");
        aMoveUp.onclick = () => {
          if (actionIndex > 0) {
            [rule.actions[actionIndex - 1], rule.actions[actionIndex]] = [rule.actions[actionIndex], rule.actions[actionIndex - 1]];
            this.onUpdate(this.config);
            this.display();
          }
        };
        if (actionIndex === 0)
          aMoveUp.disabled = true;
        const aMoveDown = aControls.createEl("button", { cls: "clickable-icon" });
        (0, import_obsidian6.setIcon)(aMoveDown, "arrow-down");
        aMoveDown.onclick = () => {
          if (actionIndex < rule.actions.length - 1) {
            [rule.actions[actionIndex + 1], rule.actions[actionIndex]] = [rule.actions[actionIndex], rule.actions[actionIndex + 1]];
            this.onUpdate(this.config);
            this.display();
          }
        };
        if (actionIndex === rule.actions.length - 1)
          aMoveDown.disabled = true;
        const configDiv = actionItem.createDiv("curator-action-config");
        const typeSelect = configDiv.createEl("select");
        ["move", "rename", "tag", "update"].forEach((t) => {
          const opt = typeSelect.createEl("option", { text: t, value: t });
          if (t === action.type)
            opt.selected = true;
        });
        typeSelect.onchange = () => {
          action.type = typeSelect.value;
          if (action.type === "move")
            action.config = { folder: "" };
          else if (action.type === "rename")
            action.config = { prefix: "", suffix: "" };
          else if (action.type === "tag")
            action.config = { tag: "", operation: "add" };
          else if (action.type === "update")
            action.config = { key: "", value: "" };
          this.onUpdate(this.config);
          this.display();
        };
        if (action.type === "move") {
          const folderInput = configDiv.createEl("input", { type: "text" });
          folderInput.placeholder = "Folder Path";
          folderInput.value = action.config.folder || "";
          new FolderSuggest(this.app, folderInput);
          folderInput.oninput = () => {
            action.config.folder = folderInput.value;
            this.onUpdate(this.config);
          };
        } else if (action.type === "tag") {
          const tagInput = configDiv.createEl("input", { type: "text" });
          tagInput.placeholder = "#tag";
          tagInput.value = action.config.tag || "";
          tagInput.oninput = () => {
            action.config.tag = tagInput.value;
            this.onUpdate(this.config);
          };
          const opSelect = configDiv.createEl("select");
          ["add", "remove"].forEach((op) => {
            const opt = opSelect.createEl("option", { text: op, value: op });
            if (op === action.config.operation)
              opt.selected = true;
          });
          opSelect.onchange = () => {
            action.config.operation = opSelect.value;
            this.onUpdate(this.config);
          };
        } else if (action.type === "update") {
          const keyInput = configDiv.createEl("input", { type: "text" });
          keyInput.placeholder = "Property Key";
          keyInput.value = action.config.key || "";
          keyInput.oninput = () => {
            action.config.key = keyInput.value;
            this.onUpdate(this.config);
          };
          const valInput = configDiv.createEl("input", { type: "text" });
          valInput.placeholder = "Value";
          valInput.value = action.config.value || "";
          valInput.oninput = () => {
            action.config.value = valInput.value;
            this.onUpdate(this.config);
          };
        } else if (action.type === "rename") {
          const prefixInput = configDiv.createEl("input", { type: "text" });
          prefixInput.placeholder = "Prefix";
          prefixInput.value = action.config.prefix || "";
          prefixInput.oninput = () => {
            action.config.prefix = prefixInput.value;
            this.onUpdate(this.config);
          };
          const suffixInput = configDiv.createEl("input", { type: "text" });
          suffixInput.placeholder = "Suffix";
          suffixInput.value = action.config.suffix || "";
          suffixInput.oninput = () => {
            action.config.suffix = suffixInput.value;
            this.onUpdate(this.config);
          };
        }
        const aDelete = actionItem.createEl("button", { cls: "clickable-icon" });
        (0, import_obsidian6.setIcon)(aDelete, "trash");
        aDelete.onclick = () => {
          rule.actions.splice(actionIndex, 1);
          this.onUpdate(this.config);
          this.display();
        };
      });
      const addActionBtn = rulesList.createEl("button", { text: "+ Add Action" });
      addActionBtn.style.marginTop = "5px";
      addActionBtn.onclick = () => {
        rule.actions.push({ type: "move", config: { folder: "" } });
        this.onUpdate(this.config);
        this.display();
      };
    });
    const addRuleBtn = body.createEl("button", { text: "+ Add Rule" });
    addRuleBtn.style.marginTop = "10px";
    addRuleBtn.onclick = () => {
      ruleset.rules.push({
        id: crypto.randomUUID(),
        query: "",
        actions: []
      });
      this.onUpdate(this.config);
      this.display();
    };
  }
};

// ui/components/LogbookTab.ts
var import_obsidian7 = __toModule(require("obsidian"));
var LogbookTab = class {
  constructor(app, containerEl, binder) {
    this.app = app;
    this.containerEl = containerEl;
    this.binder = binder;
  }
  display() {
    this.containerEl.empty();
    const header = this.containerEl.createDiv("logbook-header");
    header.style.display = "flex";
    header.style.justifyContent = "space-between";
    header.style.alignItems = "center";
    header.style.marginBottom = "10px";
    const headerH3 = header.createEl("h3", { text: "Logbook" });
    headerH3.style.margin = "0";
    new import_obsidian7.ButtonComponent(header).setButtonText("Clear Log").setWarning().onClick(() => {
      this.binder.clear();
      this.display();
    });
    const entries = this.binder.getEntries();
    const logContainer = this.containerEl.createDiv("curator-logbook");
    logContainer.style.height = "400px";
    logContainer.style.overflowY = "auto";
    logContainer.style.border = "1px solid var(--background-modifier-border)";
    logContainer.style.padding = "10px";
    logContainer.style.borderRadius = "4px";
    logContainer.style.backgroundColor = "var(--background-primary)";
    logContainer.style.fontFamily = "monospace";
    if (entries.length === 0) {
      const emptyMsg = logContainer.createDiv({ text: "No entries found." });
      emptyMsg.style.color = "var(--text-muted)";
      emptyMsg.style.textAlign = "center";
      emptyMsg.style.padding = "20px";
      return;
    }
    entries.forEach((entry) => {
      const entryEl = logContainer.createDiv("curator-log-entry");
      entryEl.style.marginBottom = "4px";
      entryEl.style.borderBottom = "1px solid var(--background-modifier-border)";
      entryEl.style.paddingBottom = "4px";
      const timeSpan = entryEl.createSpan({ text: `[${new Date(entry.timestamp).toLocaleTimeString()}] `, cls: "curator-log-time" });
      timeSpan.style.color = "var(--text-muted)";
      const typeSpan = entryEl.createSpan({ text: entry.type.toUpperCase(), cls: `curator-log-type-${entry.type}` });
      typeSpan.style.fontWeight = "bold";
      typeSpan.style.marginRight = "5px";
      if (entry.type === "error")
        typeSpan.style.color = "var(--text-error)";
      else if (entry.type === "warning")
        typeSpan.style.color = "var(--text-warning)";
      else if (entry.type === "success")
        typeSpan.style.color = "var(--text-success)";
      else
        typeSpan.style.color = "var(--text-normal)";
      entryEl.createSpan({ text: `: ${entry.message}`, cls: "curator-log-message" });
      if (entry.relatedFile) {
        const fileSpan = entryEl.createSpan({ text: ` (${entry.relatedFile})`, cls: "curator-log-file" });
        fileSpan.style.color = "var(--text-accent)";
      }
    });
  }
};

// ui/CuratorSettingsTab.ts
var CuratorSettingsTab = class extends import_obsidian8.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.activeTab = "rules";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Curator Settings" });
    const navContainer = containerEl.createDiv("curator-nav");
    navContainer.style.display = "flex";
    navContainer.style.gap = "10px";
    navContainer.style.marginBottom = "20px";
    this.createNavButton(navContainer, "Rules", "rules");
    this.createNavButton(navContainer, "Logbook", "logbook");
    const contentContainer = containerEl.createDiv("curator-content");
    if (this.activeTab === "rules") {
      new RulesTab(this.app, contentContainer, this.plugin.settings, (newConfig) => {
        this.plugin.settings = newConfig;
        this.plugin.saveSettings();
      }).display();
    } else if (this.activeTab === "logbook") {
      new LogbookTab(this.app, contentContainer, this.plugin.binder).display();
    }
  }
  createNavButton(container, text, tab) {
    const btn = container.createEl("button", { text });
    if (this.activeTab === tab) {
      btn.addClass("mod-cta");
    }
    btn.onclick = () => {
      this.activeTab = tab;
      this.display();
    };
  }
};

// main.ts
var AutoNoteMover = class extends import_obsidian9.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.binder = new BinderService(this.app);
      this.groupService = new GroupService(this.app);
      this.triggerService = new TriggerService(this.app);
      this.actionService = new ActionService(this.app, this.binder);
      this.rulesetService = new RulesetService(this.app, this.triggerService, this.groupService, this.binder, this.actionService);
      this.triggerService.initializeListeners();
      this.addSettingTab(new CuratorSettingsTab(this.app, this));
      this.rulesetService.updateConfig(this.settings);
    });
  }
  onunload() {
    this.triggerService.unload();
  }
  loadSettings() {
    return __async(this, null, function* () {
      const DEFAULT_SETTINGS = {
        rulesets: []
      };
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
      if (this.rulesetService) {
        this.rulesetService.updateConfig(this.settings);
      }
    });
  }
};
